// Metadata for all @mosta packages
// Author: Dr Hamid MADANI drmdh@msn.com

export interface PackageInfo {
  name: string
  npm: string
  description: string
  icon: string
  color: string
  features: string[]
  exports: string[]
  dependencies: string[]
  href: string
}

export const packages: PackageInfo[] = [
  {
    name: 'ORM',
    npm: '@mostajs/orm',
    description: 'Hibernate-inspired multi-dialect ORM — One API, 13 databases, zero lock-in.',
    icon: '🗄️',
    color: 'from-blue-500 to-cyan-500',
    features: [
      '13 database dialects',
      'Repository pattern with generics',
      'Relations (1:1, 1:N, M:N)',
      'Aggregation pipeline',
      'Lazy driver loading',
      'Schema strategies',
    ],
    exports: ['createConnection', 'BaseRepository', 'EntitySchema', 'registerSchema', 'getDialect'],
    dependencies: [],
    href: '/packages/orm',
  },
  {
    name: 'Auth',
    npm: '@mostajs/auth',
    description: 'Authentication & RBAC — NextAuth + Users + Roles + Permissions.',
    icon: '🔐',
    color: 'from-green-500 to-emerald-500',
    features: [
      'NextAuth 5 integration',
      'Role-based access control',
      'Permission checking (server & client)',
      'RBAC seed function',
      'Middleware factory',
      'React hooks & guards',
    ],
    exports: ['createAuthHandlers', 'createAuthChecks', 'seedRBAC', 'usePermissions', 'PermissionGuard'],
    dependencies: ['@mostajs/orm'],
    href: '/packages/auth',
  },
  {
    name: 'Audit',
    npm: '@mostajs/audit',
    description: 'Audit logging — fire-and-forget logAudit() with paginated consultation.',
    icon: '📋',
    color: 'from-amber-500 to-orange-500',
    features: [
      'Fire-and-forget logging',
      'Paginated consultation API',
      'Resource-based queries',
      'Retention management',
      'Filter by module/action/user',
    ],
    exports: ['logAudit', 'getAuditUser', 'AuditLogRepository', 'createAuditHandlers'],
    dependencies: ['@mostajs/orm'],
    href: '/packages/audit',
  },
  {
    name: 'Settings',
    npm: '@mostajs/settings',
    description: 'Key-value settings with typed factory, React provider, and auto-generated form.',
    icon: '⚙️',
    color: 'from-purple-500 to-violet-500',
    features: [
      'Typed settings factory',
      'React context provider',
      'Auto-generated admin form',
      'Validation support',
      'Settings grouping',
    ],
    exports: ['createSettingsModule', 'SettingsProvider', 'SettingsForm', 'useSettings'],
    dependencies: ['@mostajs/orm'],
    href: '/packages/settings',
  },
  {
    name: 'Setup',
    npm: '@mostajs/setup',
    description: 'Setup wizard — multi-dialect DB configuration, .env writer, seed runner.',
    icon: '🚀',
    color: 'from-rose-500 to-pink-500',
    features: [
      '13 dialect configuration',
      'DB connection testing',
      'URI auto-composition',
      '.env.local writer',
      'RBAC + admin seeding',
    ],
    exports: ['needsSetup', 'runInstall', 'testDbConnection', 'composeDbUri', 'DIALECT_INFO'],
    dependencies: ['@mostajs/orm'],
    href: '/packages/setup',
  },
  {
    name: 'Face',
    npm: '@mostajs/face',
    description: 'Face recognition — detection, descriptor extraction, 1:N matching.',
    icon: '👤',
    color: 'from-teal-500 to-cyan-500',
    features: [
      'Face detection with landmarks',
      '128-dim descriptor extraction',
      '1:N face matching',
      'React camera hook',
      'Continuous detection hook',
    ],
    exports: ['loadModels', 'detectFace', 'extractDescriptor', 'findMatch', 'useCamera', 'FaceDetector', 'FaceSettings'],
    dependencies: [],
    href: '/packages/face',
  },
  {
    name: 'RBAC',
    npm: '@mostajs/rbac',
    description: 'Role-Based Access Control — roles, permissions, categories, matrix, seed, admin pages.',
    icon: '🛡️',
    color: 'from-indigo-500 to-blue-500',
    features: [
      'Permission categories',
      'Role-permission matrix',
      'RBAC seed function',
      'Admin pages (users, roles)',
      'Route factories for CRUD',
    ],
    exports: ['createUsersHandler', 'createRolesHandler', 'createSeedHandler', 'createMatrixHandler'],
    dependencies: ['@mostajs/orm', '@mostajs/auth'],
    href: '/packages/rbac',
  },
  {
    name: 'Ticketing',
    npm: '@mostajs/ticketing',
    description: 'Ticket generation & scan validation — Wiegand 24-bit format, multi-mode access.',
    icon: '🎫',
    color: 'from-yellow-500 to-amber-500',
    features: [
      'Wiegand 24-bit ticket numbers',
      '8-step scan validation pipeline',
      'Validity modes (day_reentry, single_use, time_slot)',
      'Quota management',
      'Activity & subscription plans',
    ],
    exports: ['createTicketsHandler', 'createScanHandler', 'TicketRepository', 'processScan'],
    dependencies: ['@mostajs/orm'],
    href: '/packages/ticketing',
  },
  {
    name: 'UI',
    npm: '@mostajs/ui',
    description: 'Shared UI library — 18 shadcn/Radix components with Tailwind CSS.',
    icon: '🎨',
    color: 'from-pink-500 to-rose-500',
    features: [
      '18 shadcn/radix primitives',
      'Button, Card, Dialog, Table, Tabs',
      'Select, Input, Label, Badge',
      'Tooltip, Popover, DropdownMenu',
      'cn() utility for Tailwind merge',
    ],
    exports: ['Button', 'Card', 'Dialog', 'Table', 'Input', 'Select', 'Badge', 'cn'],
    dependencies: [],
    href: '/packages/ui',
  },
  {
    name: 'Menu',
    npm: '@mostajs/menu',
    description: 'Dashboard sidebar — configurable menu with RBAC-based item filtering.',
    icon: '📑',
    color: 'from-sky-500 to-blue-500',
    features: [
      'Declarative MenuConfig',
      'Permission-based filtering',
      'Collapsible sidebar',
      'Auto-expand active group',
      'i18n support',
    ],
    exports: ['DashboardSidebar', 'MenuConfig', 'MenuItem', 'MenuGroup'],
    dependencies: [],
    href: '/packages/menu',
  },
  {
    name: 'Scan',
    npm: '@mostajs/scan',
    description: 'QR/barcode scanner UI — webcam scanner, result cards, audio feedback.',
    icon: '📷',
    color: 'from-emerald-500 to-green-500',
    features: [
      'QR scanner via html5-qrcode',
      'Audio feedback (granted/denied)',
      'ScanResultCard component',
      'useScan() hook',
      'Configurable API endpoint',
    ],
    exports: ['ScannerView', 'ScanResultCard', 'useScan', 'playBeep'],
    dependencies: [],
    href: '/packages/scan',
  },
  {
    name: 'Init',
    npm: '@mostajs/init',
    description: 'CLI & codegen — module discovery, CRUD generator, schema/page visual designers.',
    icon: '🧙',
    color: 'from-violet-500 to-purple-500',
    features: [
      'CLI module discovery (npx)',
      'CRUD page generator',
      'DAL registry/service codegen',
      'Visual Schema Designer',
      'Visual Page Designer',
      'Database reverse engineering',
    ],
    exports: ['discoverModules', 'generateCrud', 'SchemaDesigner', 'PageDesigner', 'reverseEngineerMongo'],
    dependencies: [],
    href: '/packages/init',
  },
  {
    name: 'Media',
    npm: '@mostajs/media',
    description: 'Image & video capture — webcam, screen recording, editor, gallery, debug recorder.',
    icon: '🎬',
    color: 'from-red-500 to-orange-500',
    features: [
      'Webcam image capture',
      'Video recording (webcam + screen)',
      'Screen + webcam overlay',
      'Image editor (rotate, crop, brightness)',
      'Floating debug recorder widget',
      'Media gallery with lightbox',
    ],
    exports: ['ImageCapture', 'VideoCapture', 'ScreenRecorder', 'ImageEditor', 'useCamera', 'useScreenCapture'],
    dependencies: [],
    href: '/packages/media',
  },
]

export const databases = [
  { name: 'MongoDB', icon: '🍃', category: 'Document', driver: 'mongoose' },
  { name: 'SQLite', icon: '📄', category: 'File', driver: 'better-sqlite3' },
  { name: 'PostgreSQL', icon: '🐘', category: 'SQL', driver: 'pg' },
  { name: 'MySQL', icon: '🐬', category: 'SQL', driver: 'mysql2' },
  { name: 'MariaDB', icon: '🦭', category: 'SQL', driver: 'mariadb' },
  { name: 'Oracle', icon: '🔴', category: 'Enterprise', driver: 'oracledb' },
  { name: 'SQL Server', icon: '🟦', category: 'Enterprise', driver: 'mssql' },
  { name: 'CockroachDB', icon: '🪳', category: 'Distributed', driver: 'pg' },
  { name: 'IBM DB2', icon: '🏢', category: 'Enterprise', driver: 'ibm_db' },
  { name: 'SAP HANA', icon: '💎', category: 'Enterprise', driver: '@sap/hana-client' },
  { name: 'HyperSQL', icon: '⚡', category: 'Legacy', driver: 'HTTP bridge' },
  { name: 'Google Spanner', icon: '☁️', category: 'Distributed', driver: '@google-cloud/spanner' },
  { name: 'Sybase ASE', icon: '🔷', category: 'Legacy', driver: 'mssql' },
]
